version: '2'

services:

  postgres:
    image: postgres:10.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "docly"
      POSTGRES_PASSWORD: "1234"

  backend:
    ports:
      - "3000:3000"
    build:
      context: .
    restart:
      always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: docly
      POSTGRES_USER: docly
      POSTGRES_PASS: 1234
    volumes: 
      - '.:/usr/src/app'
    command: bash -c "npm install && npm start"
